# Generated by Django 5.1 on 2024-08-26 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('images', models.ImageField(upload_to='products/')),
                ('description', models.TextField()),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SKU', models.CharField(max_length=100, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='api.category')),
            ],
        ),
    ]
