# Generated by Django 3.2 on 2024-09-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
