# Generated by Django 3.2 on 2024-09-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_productimage_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage_product',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
